//jabhi poora andar ka of object u are unable to see
//then console.dir(objectName)
///basically when working on optimize other browsers
//for in loops over enumerable property names of an object.
//for of (new in ES6) does use an object-specific iterator and loops over the values generated by that.
//in javascript this keyword is set on the method the object is called on
